package alternativa.engine3d.core;

extern class Object3D {
	var _parent : Object3DContainer;
	var alpha : Float;
	var blendMode : String;
	var boundMaxX : Float;
	var boundMaxY : Float;
	var boundMaxZ : Float;
	var boundMinX : Float;
	var boundMinY : Float;
	var boundMinZ : Float;
	var bubbleListeners : Dynamic;
	var captureListeners : Dynamic;
	var colorTransform : flash.geom.ColorTransform;
	var culling : Int;
	var distance : Float;
	var doubleClickEnabled : Bool;
	var filters : Array<Dynamic>;
	var ima : Float;
	var imb : Float;
	var imc : Float;
	var imd : Float;
	var ime : Float;
	var imf : Float;
	var img : Float;
	var imh : Float;
	var imi : Float;
	var imj : Float;
	var imk : Float;
	var iml : Float;
	var ma : Float;
	var matrix : flash.geom.Matrix3D;
	var mb : Float;
	var mc : Float;
	var md : Float;
	var me : Float;
	var mf : Float;
	var mg : Float;
	var mh : Float;
	var mi : Float;
	var mj : Float;
	var mk : Float;
	var ml : Float;
	var mouseEnabled : Bool;
	var name : String;
	var next : Object3D;
	var parent(default,null) : Object3DContainer;
	var rotationX : Float;
	var rotationY : Float;
	var rotationZ : Float;
	var scaleX : Float;
	var scaleY : Float;
	var scaleZ : Float;
	var transformId : Int;
	var visible : Bool;
	var weightsSum : flash.Vector<Float>;
	var x : Float;
	var y : Float;
	var z : Float;
	function new() : Void;
	function addEventListener(p0 : String, p1 : Dynamic, ?p2 : Bool, ?p3 : Int, ?p4 : Bool) : Void;
	function appendMatrix(p0 : Object3D) : Void;
	function boundIntersectRay(p0 : flash.geom.Vector3D, p1 : flash.geom.Vector3D, p2 : Float, p3 : Float, p4 : Float, p5 : Float, p6 : Float, p7 : Float) : Bool;
	function calculateBounds() : Void;
	function calculateInverseMatrix() : Void;
	function calculatePlane(p0 : flash.geom.Vector3D, p1 : flash.geom.Vector3D, p2 : flash.geom.Vector3D) : flash.geom.Vector3D;
	function calculateResolution(p0 : Int, p1 : Int, ?p2 : Int, ?p3 : flash.geom.Matrix3D) : Float;
	function clone() : Object3D;
	function composeAndAppend(p0 : Object3D) : Void;
	function composeMatrix() : Void;
	function cullingInCamera(p0 : Camera3D, p1 : Int) : Int;
	function dispatchEvent(p0 : flash.events.Event) : Bool;
	function draw(p0 : Camera3D, p1 : Canvas) : Void;
	function getVG(p0 : Camera3D) : VG;
	function globalToLocal(p0 : flash.geom.Vector3D) : flash.geom.Vector3D;
	function hasEventListener(p0 : String) : Bool;
	function intersectRay(p0 : flash.geom.Vector3D, p1 : flash.geom.Vector3D, ?p2 : flash.utils.Dictionary, ?p3 : Camera3D) : RayIntersectionData;
	function invertMatrix() : Void;
	function localToGlobal(p0 : flash.geom.Vector3D) : flash.geom.Vector3D;
	function removeEventListener(p0 : String, p1 : Dynamic, ?p2 : Bool) : Void;
	function removeFromParent() : Void;
	function split(p0 : flash.geom.Vector3D, p1 : flash.geom.Vector3D, p2 : flash.geom.Vector3D, p3 : Float) : flash.Vector<Object3D>;
	function testSplit(p0 : flash.geom.Vector3D, p1 : flash.geom.Vector3D, p2 : flash.geom.Vector3D, p3 : Float) : Int;
	function toString() : String;
	function updateBounds(p0 : Object3D, ?p1 : Object3D) : Void;
	function willTrigger(p0 : String) : Bool;
	private function clonePropertiesFrom(p0 : Object3D) : Void;
}
